### ISSUE TITLE
Make docs

### ISSUE THREAD

**Issue by NoodlesDev987** [Vicente015/instatus.ts#2]
Suggestion: Make docs also with examples.

**Comment by Vicente015** [comment]
Hi, thank you for being interested in this project
I will make your suggestion to improve the documentation and provide better examples, I'll try to get on with this later

**Comment by Vicente015** [comment]
Finally I have built a new documentation and added some examples :D! I will add more examples and in the next few days

You can see it from https://instatus.vicente015.dev

![imagen](https://user-images.githubusercontent.com/33096355/115122114-20e5f780-9fae-11eb-9d81-e9e3eab62d64.png)


![imagen](https://user-images.githubusercontent.com/33096355/115122107-17f52600-9fae-11eb-80d9-288dee29f1e1.png)
